// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { CreateOneTimeJobData, CreateOneTimeJobError, CreateOneTimeJobResponse, CreateCronJobJobsCronPostData, CreateCronJobJobsCronPostError, CreateCronJobJobsCronPostResponse, GetJobJobsJobIdGetData, RemoveJobJobsJobIdDeleteData, RemoveJobJobsJobIdDeleteError, RemoveJobJobsJobIdDeleteResponse } from '../types.gen';
import { client, createOneTimeJob, createCronJobJobsCronPost, getJobJobsJobIdGet, removeJobJobsJobIdDelete, getAllJobs } from '../services.gen';

type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};

export const createOneTimeJobQueryKey = (options: Options<CreateOneTimeJobData>) => [
    createQueryKey("createOneTimeJob", options)
];

export const createOneTimeJobOptions = (options: Options<CreateOneTimeJobData>) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await createOneTimeJob({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: createOneTimeJobQueryKey(options)
}); };

export const createOneTimeJobMutation = () => { const mutationOptions: UseMutationOptions<CreateOneTimeJobResponse, CreateOneTimeJobError, Options<CreateOneTimeJobData>> = {
    mutationFn: async (options) => {
        const { data } = await createOneTimeJob({
            ...options,
            throwOnError: true
        });
        return data;
    }
}; return mutationOptions; };

export const createCronJobJobsCronPostQueryKey = (options: Options<CreateCronJobJobsCronPostData>) => [
    createQueryKey("createCronJobJobsCronPost", options)
];

export const createCronJobJobsCronPostOptions = (options: Options<CreateCronJobJobsCronPostData>) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await createCronJobJobsCronPost({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: createCronJobJobsCronPostQueryKey(options)
}); };

export const createCronJobJobsCronPostMutation = () => { const mutationOptions: UseMutationOptions<CreateCronJobJobsCronPostResponse, CreateCronJobJobsCronPostError, Options<CreateCronJobJobsCronPostData>> = {
    mutationFn: async (options) => {
        const { data } = await createCronJobJobsCronPost({
            ...options,
            throwOnError: true
        });
        return data;
    }
}; return mutationOptions; };

export const getJobJobsJobIdGetQueryKey = (options: Options<GetJobJobsJobIdGetData>) => [
    createQueryKey("getJobJobsJobIdGet", options)
];

export const getJobJobsJobIdGetOptions = (options: Options<GetJobJobsJobIdGetData>) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await getJobJobsJobIdGet({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobJobsJobIdGetQueryKey(options)
}); };

export const removeJobJobsJobIdDeleteMutation = () => { const mutationOptions: UseMutationOptions<RemoveJobJobsJobIdDeleteResponse, RemoveJobJobsJobIdDeleteError, Options<RemoveJobJobsJobIdDeleteData>> = {
    mutationFn: async (options) => {
        const { data } = await removeJobJobsJobIdDelete({
            ...options,
            throwOnError: true
        });
        return data;
    }
}; return mutationOptions; };

export const getAllJobsQueryKey = (options?: Options) => [
    createQueryKey("getAllJobs", options)
];

export const getAllJobsOptions = (options?: Options) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await getAllJobs({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllJobsQueryKey(options)
}); };