// This file is auto-generated by @hey-api/openapi-ts

export const APIRequestSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url',
            examples: ['http://127.0.0.1:8000']
        },
        method: {
            type: 'string',
            title: 'Method',
            default: 'POST'
        },
        headers: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Headers',
            default: {}
        },
        body: {
            title: 'Body',
            examples: [
                {}
            ]
        }
    },
    type: 'object',
    required: ['url'],
    title: 'APIRequest'
} as const;

export const CronJobSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id',
            examples: [
                null
            ]
        },
        request: {
            '$ref': '#/components/schemas/APIRequest'
        },
        cron: {
            type: 'string',
            title: 'Cron',
            examples: ['* * * * *']
        }
    },
    type: 'object',
    required: ['request', 'cron'],
    title: 'CronJob'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const JobStatusSchema = {
    type: 'string',
    enum: ['pending', 'active', 'paused'],
    title: 'JobStatus'
} as const;

export const OneTimeJobSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id',
            examples: [
                null
            ]
        },
        request: {
            '$ref': '#/components/schemas/APIRequest'
        },
        delay: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delay'
        },
        date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        }
    },
    type: 'object',
    required: ['request'],
    title: 'OneTimeJob'
} as const;

export const ScheduledJobSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id',
            examples: [
                null
            ]
        },
        request: {
            '$ref': '#/components/schemas/APIRequest'
        },
        next_run_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Run Time'
        },
        status: {
            '$ref': '#/components/schemas/JobStatus'
        }
    },
    type: 'object',
    required: ['request', 'next_run_time', 'status'],
    title: 'ScheduledJob'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;