// This file is auto-generated by @hey-api/openapi-ts

export type APIRequest = {
    url: string;
    method?: string;
    headers?: {
        [key: string]: (string);
    };
    body?: unknown;
};

export type Callback = {
    id?: (string | null);
    request: APIRequest;
};

export type CronJob = {
    id?: (string | null);
    request: APIRequest;
    cron: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type OneTimeJob = {
    id?: (string | null);
    request: APIRequest;
    delay?: (number | null);
    date?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CreateOneTimeJobJobsJobsOneTimePostData = {
    body: OneTimeJob;
};

export type CreateOneTimeJobJobsJobsOneTimePostResponse = (unknown);

export type CreateOneTimeJobJobsJobsOneTimePostError = (HTTPValidationError);

export type CreateCronJobJobsJobsCronPostData = {
    body: CronJob;
};

export type CreateCronJobJobsJobsCronPostResponse = (unknown);

export type CreateCronJobJobsJobsCronPostError = (HTTPValidationError);

export type GetJobJobsJobsJobIdGetData = {
    path: {
        job_id: string;
    };
};

export type GetJobJobsJobsJobIdGetResponse = ((Callback | null));

export type GetJobJobsJobsJobIdGetError = (HTTPValidationError);

export type RemoveJobJobsJobsJobIdDeleteData = {
    path: {
        job_id: string;
    };
};

export type RemoveJobJobsJobsJobIdDeleteResponse = (unknown);

export type RemoveJobJobsJobsJobIdDeleteError = (HTTPValidationError);

export type GetAllJobsJobsJobsGetResponse = (Array<Callback>);

export type GetAllJobsJobsJobsGetError = unknown;