// This file is auto-generated by @hey-api/openapi-ts

export const APIRequestSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url',
            examples: ['http://127.0.0.1:8000']
        },
        method: {
            type: 'string',
            title: 'Method',
            default: 'POST'
        },
        headers: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Headers',
            default: {}
        },
        body: {
            title: 'Body',
            examples: [
                {}
            ]
        }
    },
    type: 'object',
    required: ['url'],
    title: 'APIRequest'
} as const;

export const APIResponseSchema = {
    properties: {
        status_code: {
            type: 'integer',
            title: 'Status Code'
        },
        headers: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Headers',
            default: {}
        },
        body: {
            title: 'Body',
            examples: [
                {}
            ]
        }
    },
    type: 'object',
    required: ['status_code'],
    title: 'APIResponse'
} as const;

export const CronTriggerCreateSchema = {
    properties: {
        cron: {
            type: 'string',
            title: 'Cron',
            examples: ['* * * * *']
        }
    },
    type: 'object',
    required: ['cron'],
    title: 'CronTriggerCreate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const JobCreateSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id',
            examples: [
                null
            ]
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name',
            examples: [
                null
            ]
        },
        request: {
            '$ref': '#/components/schemas/APIRequest'
        },
        trigger: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OneTimeTriggerCreate'
                },
                {
                    '$ref': '#/components/schemas/CronTriggerCreate'
                }
            ],
            title: 'Trigger',
            examples: [
                {
                    delay: 1
                }
            ]
        }
    },
    type: 'object',
    required: ['request', 'trigger'],
    title: 'JobCreate'
} as const;

export const JobResultSchema = {
    properties: {
        completed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Completed At'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        response: {
            '$ref': '#/components/schemas/APIResponse'
        }
    },
    type: 'object',
    required: ['completed_at', 'response'],
    title: 'JobResult'
} as const;

export const JobStatusSchema = {
    type: 'string',
    enum: ['pending', 'active', 'paused', 'completed-successful', 'completed-request-error', 'completed-response-error', 'completed-warning'],
    title: 'JobStatus'
} as const;

export const OneTimeTriggerCreateSchema = {
    properties: {
        delay: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delay'
        },
        date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        }
    },
    type: 'object',
    title: 'OneTimeTriggerCreate'
} as const;

export const ScheduledJobSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        next_run_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Run Time'
        },
        status: {
            '$ref': '#/components/schemas/JobStatus'
        },
        trigger: {
            '$ref': '#/components/schemas/Trigger'
        },
        request: {
            '$ref': '#/components/schemas/APIRequest'
        },
        result: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/JobResult'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'created_at', 'status', 'trigger', 'request'],
    title: 'ScheduledJob'
} as const;

export const TriggerSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/TriggerType'
        },
        fields: {
            title: 'Fields',
            examples: [
                {}
            ]
        }
    },
    type: 'object',
    required: ['type', 'fields'],
    title: 'Trigger'
} as const;

export const TriggerTypeSchema = {
    type: 'string',
    enum: ['one-time', 'cron'],
    title: 'TriggerType'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;