// This file is auto-generated by @hey-api/openapi-ts

export type APIRequest = {
    url: string;
    method?: string;
    headers?: {
        [key: string]: (string);
    };
    body?: unknown;
};

export type CronJob = {
    id?: (string | null);
    request: APIRequest;
    cron: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type JobStatus = 'pending' | 'active' | 'paused';

export type OneTimeJob = {
    id?: (string | null);
    request: APIRequest;
    delay?: (number | null);
    date?: (string | null);
};

export type ScheduledJob = {
    id?: (string | null);
    request: APIRequest;
    next_run_time: (string | null);
    status: JobStatus;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CreateOneTimeJobData = {
    body: OneTimeJob;
};

export type CreateOneTimeJobResponse = (unknown);

export type CreateOneTimeJobError = (HTTPValidationError);

export type CreateCronJobJobsCronPostData = {
    body: CronJob;
};

export type CreateCronJobJobsCronPostResponse = (unknown);

export type CreateCronJobJobsCronPostError = (HTTPValidationError);

export type GetJobJobsJobIdGetData = {
    path: {
        job_id: string;
    };
};

export type GetJobJobsJobIdGetResponse = ((ScheduledJob | null));

export type GetJobJobsJobIdGetError = (HTTPValidationError);

export type RemoveJobJobsJobIdDeleteData = {
    path: {
        job_id: string;
    };
};

export type RemoveJobJobsJobIdDeleteResponse = (unknown);

export type RemoveJobJobsJobIdDeleteError = (HTTPValidationError);

export type GetAllJobsResponse = (Array<ScheduledJob>);

export type GetAllJobsError = unknown;